package Grilla;

import Entidad.EntidadGrafica;
import Entidad.Pacman;
import Logica.Juego;

public class NivelTres extends Nivel {

	public NivelTres(Juego j, Grilla g) {
		super(j, g);
		mapa = new String[]{"PPPPPPPPPPPPPPPPPPPPPPPPPPPP",
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAA",
				"AMMMMMMMMMMMMMMMMMMMMMMMMMMA",
				"AMAAAAAAAAAAAAAAAAAAAAAAAAMA",
				"AMMMMMMMMMAAMMMMAAMMMMMMMMMA",
				"AMAAAAAAAMAAMAAMAAMAAAAAAAMA",
				"AMAAAAAAAMAAMAAMAAMAAAAAAAMA",
				"AMAAMMMMMMMMMAAMMMMMMMMMAAMA",
				"AMAAMAAMAAAAMAAMAAAAMAAMAAMA",
				"AMMMMAAMAAAAMAAMAAAAMAAMMMMA",
				"AAAAMAAMAAAAMAAMAAAAMAAMAAAA",
				"AAAAMAAMMMMMMMMMMMMMMAAMAAAA",
				"MMMMMAAAAMAAAAAAAAMAAAAMMMMM",
				"AMAAMAAAAMAAAAAAAAMAAAAMAAMA",
				"AMAAMMMMMMMMMMMMMMMMMMMMAAMA",
				"AMAAAAMAAMAAAPPAAAMAAMAAAAMA",
				"AMAAAAMAAMAPPPPPPAMAAMAAAAMA",
				"AMMMMMMAAMAPPPPPPAMAAMMMMMMA",
				"AMAAMAAAAMAPPPPPPAMAAAAMAAMA",
				"AMAAMAAAANAAAAAAAANAAAAMAAMA",
				"AMAAMMMMMMMMMMMMMMMMMMMMAAMA",
				"AMAAAAMAAAAAMAAMAAAAAMAAAAMA",
				"AMAAAAMAAAAAMAAMAAAAAMAAAAMA",
				"AMMMMMMAAMMMMAAMMMMAAMMMMMMA",
				"AAAMAAMAAMAAAAAAAAMAAMAAMAAA",
				"AAAMAAMAAMAAAAAAAAMAAMAAMAAA",
				"AMMMAAMMMMMMMMMMMMMMMMAAMMMA",
				"AMAAAAMAAAAAMAAMAAAAAMAAAAMA",
				"AMAAAAMAAAAAMAAMAAAAAMAAAAMA",
				"AMMMMMMAAMMMMAAMMMMAAMMMMMMA",
				"AMAAAAMAAMAAAAAAAAMAAMAAAAMA",
				"AMAAAAMAAMAAAAAAAAMAAMAAAAMA",
				"AMMMMMMAAMMMMMMMMMMAAMMMMMMA",
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAA",
				"PPPPPPPPPPPPPPPPPPPPPPPPPPPP",
				"PPPPPPPPPPPPPPPPPPPPPPPPPPPP"};
	}

	@Override
	protected void agregarEntidadesMoviles(Bloque[][] m) {
		pacman = new Pacman(15, 26, g);
		EntidadGrafica egPacman = new EntidadGrafica(pacman);
		pacman.setEntidadGrafica(egPacman);
		m[3][3].agregarEntidad(pacman);
		g.agregarLabel(egPacman);
	}

}
