package Grilla;

import Entidad.EntidadGrafica;
import Entidad.Pacman;
import Logica.Juego;

public class NivelDos extends Nivel {

	public NivelDos(Juego j, Grilla g) {
		super(j, g);
		mapa = new String[]{"PPPPPPPPPPPPPPPPPPPPPPPPPPPP",
				"PPPPPPPPPPPPPPPPPPPPPPPPPPPP",
				"PPPPPPAAAAAAAAAAAAAAAAPPPPPP",
				"PPPAAAAMMMMMMMMMMMMMMAAAAPPP",
				"PPAAMMMMAAMAAAAAAMAAMMMMAAPP",
				"PAAMMAAMAAMAAAAAAMAAMAAMMAAP",
				"AAMMAAAMAAMMMAAMMMAAMAAAMMAA",
				"AMMAAPAMAAAAMAAMAAAAMAPAAMMA",
				"AMAAAAAMAAAAMAAMAAAAMAAAAAMA",
				"AMMMMMMMAAMMMMMMMMAAMMMMMMMA",
				"AAAMAAAAAAMAAAAAAMAAAAAAMAAA",
				"AAAMAAAAAAMAAAAAAMAAAAAAMAAA",
				"AMMMMMMMAAMMMAAMMMAAMMMMMMMA",
				"AMAAAAAMAAAAMAAMAAAAMAAAAAMA",
				"AMAAAAAMAAAAMAAMAAAAMAAAAAMA",
				"AMMMMAAMMMMMMMMMMMMMMAAMMMMA",
				"AAAAMAAAAMAAAPPAAAMAAAAMAAAA",
				"AAAAMAAAAMAPPPPPPAMAAAAMAAAA",
				"MMAAMMMMMMAPPPPPPAMMMMMMAAMM",
				"AMAAMAAAAMAPPPPPPAMAAAAMAAMA",
				"AMMMMAAAAMAAAAAAAAMAAAAMMMMA",
				"AMAAMAAMMMMMMMMMMMMMMAAMAAMA",
				"AMAAMAAMAAAAAAAAAAAAMAAMAAMA",
				"AMAAMAAMAAAAAAAAAAAAMAAMAAMA",
				"MMAAMAAMMMMMMAAMMMMMMAAMAAMM",
				"AAAAMAAAAAAAMAAMAAAAAAAMAAAA",
				"AAAAMAAAAAAAMAAMAAAAAAAMAAAA",
				"AMMMMMMMMMMMMMMMMMMMMMMMMMMA",
				"AMAAMAAAAAAAAAAAAAAAAAAMAAMA",
				"AMAAMAPPPPPPPPPPPPPPPPAMAAMA",
				"AMAAMAPPPPPPPPPPPPPPPPAMAAMA",
				"AMAAMAPPPPPPPPPPPPPPPPAMAAMA",
				"AMMMMAPPPPPPPPPPPPPPPPAMMMMA",
				"AAAAAAPPPPPPPPPPPPPPPPAAAAAA",
				"PPPPPPPPPPPPPPPPPPPPPPPPPPPP",
				"PPPPPPPPPPPPPPPPPPPPPPPPPPPP"};
	}

	@Override
	protected void agregarEntidadesMoviles(Bloque[][] m) {
		pacman = new Pacman(15, 26, g);
		EntidadGrafica egPacman = new EntidadGrafica(pacman);
		pacman.setEntidadGrafica(egPacman);
		m[3][3].agregarEntidad(pacman);
		g.agregarLabel(egPacman);
	}

}
