package Grilla;


import Entidad.*;
import Logica.Juego;

public class NivelUno extends Nivel{
	
	public NivelUno(Juego j, Grilla g) {
		super(j, g);
		mapa = new String[]{
				"PPPPPPPPPPPPPPPPPPPPPPPPPPPP",
				"PPPPPPPPPPPPPPPPPPPPPPPPPPPP",
				"PPPPPPPPPPPPPPPPPPPPPPPPPPPP",
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAA",
				"AWMMMMMMMMMBMAAMVMMMMMMMMMWA",
				"AMAAAAMAAAAAMAAMAAAAAMAAAAMA",
				"AMAAAAMAAAAAMAAMAAAAAMAAAAMA",
				"AMAAAAMAAAAAMAAMAAAAAMAAAAMA",
				"AMMMMMMMMMMMMMMMMMMMMMMMMMMA",
				"AMAAAAMAAMAAAAAAAAMAAMAAAAMA",
				"AMAAAAMAAMAAAAAAAAMAAMAAAAMA",
				"AMMMMMMAAMMMMAAMMMMAAMMMMMMA",
				"AAAAAAMAAAAAPAAPAAAAAMAAAAAA",
				"PPPPPAMAAAAAPAAPAAAAAMAPPPPP",
				"PPPPPAMAAPPPPPPPPPPAAMAPPPPP",
				"PPPPPAMAAPAAAPPAAAPAAMAPPPPP",
				"AAAAAAMAAPAPPPPPPAPAAMAAAAAA",
				"PPPPPPMPPPAPPPPPPAPPPMPPPPPP",
				"AAAAAAMAAPAPPPPPPAPAAMAAAAAA",
				"PPPPPAMAAPAAAAAAAAPAAMAPPPPP",
				"PPPPPAMAAPPPPFPPPPPAAMAPPPPP",
				"PPPPPAMAAPAAAAAAAAPAAMAPPPPP",
				"AAAAAAMAAPAAAAAAAAPAAMAAAAAA",
				"AMMMMMMMMMMMMAAMMMMMMMMMMMMA",
				"AMAAAAMAAAAAMAAMAAAAAMAAAAMA",
				"AMAAAAMAAAAAMAAMAAAAAMAAAAMA",
				"AMMMAAMMMMMMMPPMMMMMMMAAMMMA",
				"AAAMAAMAAMAAAAAAAAMAAMAAMAAA",
				"AAAMAAMAAMAAAAAAAAMAAMAAMAAA",
				"AMMMMMMAAMMMMAAMMMMAAMMMMMMA",
				"AMAAAAAAAAAAMAAMAAAAAAAAAAMA",
				"AMAAAAAAAAAAMAAMAAAAAAAAAAMA",
				"AWMMMMMMMMMMMMMMMMMMMMMMMMWA",
				"AAAAAAAAAAAAAAAAAAAAAAAAAAAA",
				"PPPPPPPPPPPPPPPPPPPPPPPPPPPP",
				"PPPPPPPPPPPPPPPPPPPPPPPPPPPP"
				};
	}
	
	protected void agregarEntidadesMoviles(Bloque[][] m) {
		//Pacman:
		pacman = new Pacman(14, 26, g);
		EntidadGrafica egPacman = new EntidadGrafica(pacman);
		pacman.setEntidadGrafica(egPacman);
		m[14][26].agregarEntidad(pacman);
		g.agregarLabel(egPacman);
		
		//Fantasma Rojo:
		r = new FantasmaRojo(12, 17, g);
		EntidadGrafica egRojo = new EntidadGrafica(r);
		r.setEntidadGrafica(egRojo);
		m[12][17].agregarEntidad(r);
		g.agregarLabel(egRojo);
	}
}
